# Generated by Django 5.1.2 on 2024-10-29 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100)),
                ('soyad', models.CharField(max_length=100)),
                ('biyografi', models.TextField()),
                ('deneyim', models.TextField()),
                ('eğitim_durumu', models.TextField()),
                ('fotoğraf', models.ImageField(upload_to='photos/')),
            ],
        ),
    ]
